name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.githb_key }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://${GH_TOKEN}@github.com/iuru2522/desire.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"